fastlane_version '2.221.1'
default_platform :ios

platform :ios do
  desc 'Build and export the IPA file'
  lane :build_ipa do
    build_app(
      workspace: "Sample-MVVM-Swift.xcodeproj/project.xcworkspace",
      scheme: "Sample-MVVM-Swift",
      export_method: "ad-hoc"
    )
  end
end