name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10

      - name: Update RubyGems
        run: gem update --system 3.2.3

      - name: Install Bundler
        run: gem install bundler -v 2.4.22

      - name: Install Gems
        run: bundle install

      - name: Build IPA using Fastlane
        run: |
          bundle exec fastlane unit_test